### ISSUE TITLE
Set up `/admin` to redirect to Sanity Studio UI

### ISSUE THREAD

**Issue by tinymachine** [tinymachine/aiello-portfolio-site-sanity#14]
Update netlify.toml file with a redirect to https://drewaiello-edit.netlify.app. 

Sample code for Netlify:
```toml
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
```

Here's how to handle [redirects on Vercel](https://vercel.com/docs/projects/project-configuration#redirects).
